{-
   Homebank API
   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   OpenAPI spec version: v1

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Request.Account exposing (apiAccountGet)

import Data.User as User exposing (User)
import Dict
import Http
import Json.Decode as Decode


basePath : String
basePath =
    "http://localhost"


apiAccountGet : Http.Request (List User)
apiAccountGet =
    { method = "GET"
    , url = basePath ++ "/api/Account"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson (Decode.list User.decoder)
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request
