version: '3'

services:
  homebank:
    build: .
    ports:
      - "80:80"
    environment:
        DATABASE_HOST: mssql
        DATABASE_PORT: 1433
        DATABASE_USER: sa
        DATABASE_PASSWORD: "KDH4aqZCT3ZBdrf7"
        DATABASE_NAME: Homebank
    depends_on:
        - mssql
  mssql:
    image: microsoft/mssql-server-linux:2017-CU11
    ports:
        - 1433:1433
    volumes:
        - ./sql:/usr/src/app
    working_dir: /usr/src/app
    environment:
        SA_PASSWORD: "KDH4aqZCT3ZBdrf7"
        ACCEPT_EULA: "Y"
    entrypoint: sh -c 'chmod +x ./entrypoint.sh; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'